CREATE TABLE contact_links (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  platform_name VARCHAR(80) NOT NULL,
  profile_url VARCHAR(255) NOT NULL,
  icon_url VARCHAR(255) NOT NULL,
  description VARCHAR(300) NOT NULL,
  published BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);