spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ziqihome?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:ziqi0522@}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
